table sp500_daily
	lineageTag: c8db5395-1098-46aa-8dc3-90081b000615

	/// Unused in DAX measures — hidden to reduce field list noise and VertiPaq overhead.
	column Open_Price
		dataType: double
		isHidden
		lineageTag: c2be4e20-294c-4cf1-9296-ae78d837269e
		summarizeBy: sum
		sourceColumn: Open_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Unused in DAX measures — hidden to reduce field list noise and VertiPaq overhead.
	column High_Price
		dataType: double
		isHidden
		lineageTag: f8c4fdf5-6e6a-4d94-8e14-ca21314314bd
		summarizeBy: sum
		sourceColumn: High_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Unused in DAX measures — hidden to reduce field list noise and VertiPaq overhead.
	column Low_Price
		dataType: double
		isHidden
		lineageTag: f9516947-fe4f-4f9b-bb58-686c8fab1d26
		summarizeBy: sum
		sourceColumn: Low_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Unused in DAX measures — hidden to reduce field list noise and VertiPaq overhead.
	column Volume
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9d2a20ac-d9c5-4e73-b14b-5bf71452b105
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	column Historical_SP500_Return = ```
			
			VAR CurrentDate = sp500_daily[Trade_Date]
			
			-- 1. Find the exact previous trading day for the S&P 500
			VAR PreviousDate = 
			    CALCULATE(
			        MAX(sp500_daily[Trade_Date]),
			        REMOVEFILTERS(sp500_daily),
			        sp500_daily[Trade_Date] < CurrentDate
			    )
			
			-- 2. Fetch the closing price on that specific date
			VAR PreviousPrice = 
			    CALCULATE(
			        MAX(sp500_daily[SP500_Close]),
			        REMOVEFILTERS(sp500_daily),
			        sp500_daily[Trade_Date] = PreviousDate
			    )
			
			-- 3. Calculate the return
			RETURN 
			    DIVIDE(sp500_daily[SP500_Close] - PreviousPrice, PreviousPrice)
			```
		lineageTag: 86668239-91d7-43db-94ab-cca80eec99ae
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Trade_Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 22035fdb-4893-4659-8386-3f47c166ad89
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Trade_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SP500_Close
		dataType: double
		lineageTag: d7597e5a-ed5e-421b-acc4-51c110f80be6
		summarizeBy: sum
		sourceColumn: SP500_Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition sp500_daily = m
		mode: import
		source = ```
				let
				    // 1. Invoke Python to bypass Yahoo's security and fetch the dataframe
				    Source = Python.Execute("import yfinance as yf#(lf)import pandas as pd#(lf)#(lf)# Fetch S&P 500 data from 1980#(lf)df = yf.download('^GSPC', start='1980-12-12', progress=False)#(lf)#(lf)# Reset index to make Date a column#(lf)df.reset_index(inplace=True)#(lf)#(lf)# Strip timezone data so Power BI can parse it as a standard Date#(lf)df['Date'] = pd.to_datetime(df['Date']).dt.tz_localize(None)#(lf)#(lf)# Rename columns to match your exact dashboard schema#(lf)df.rename(columns={'Date': 'Trade_Date', 'Close': 'SP500_Close'}, inplace=True)#(lf)#(lf)# Select only the required columns and drop Adj Close#(lf)df = df[['Trade_Date', 'Open', 'High', 'Low', 'SP500_Close', 'Volume']]"),
				    
				    // 2. Expand the Python dictionary to extract the pandas DataFrame named 'df'
				    df1 = Source{[Name="df"]}[Value],
				    
				    // 3. Enforce strict Power BI Data Types
				    #"Changed Type" = Table.TransformColumnTypes(df1,{
				        {"Trade_Date", type date}, 
				        {"Open", type number}, 
				        {"High", type number}, 
				        {"Low", type number}, 
				        {"SP500_Close", type number}, 
				        {"Volume", Int64.Type}
				    }),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type"),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Errors",{{"Open", "Open_Price"}, {"High", "High_Price"}, {"Low", "Low_Price"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

